### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by dakom** [Yitzchok/Zmanim#10]
(similar fails in millisecond version)

ZmanimTests.ZmanimTest.Check_GetBainHasmashosRT13Point5MinutesBefore7Point083Degrees

  Expected: 2010-04-02 19:41:19.000
  But was:  2010-04-02 19:41:45.000

ZmanimTests.ZmanimTest.Check_GetPlagAlos16Point1ToTzaisGeonim7Point083Degrees

  Expected: 2010-04-02 18:23:24.000
  But was:  2010-04-02 18:23:48.000

ZmanimTests.ZmanimTest.Check_GetSofZmanShmaAlos16Point1ToTzaisGeonim7Point083Degrees

  Expected: 2010-04-02 08:56:38.000
  But was:  2010-04-02 08:56:44.000

ZmanimTests.ZmanimTest.Check_GetTzaisGeonim7Point083Degrees

  Expected: 2010-04-02 19:54:49.000
  But was:  2010-04-02 19:55:15.000

**Comment by dakom** [comment]
Note that the return does match Eliyahu's Java implementation. Specifically, going to http://kosherjava.com/maps/zmanim.html?lat=40.09596&lng=-74.22213&zoom=3&date=2014-04-02 and checking "more zmanim" does show that "Bain Hasmashos Rabainu Tam 13.5 minutes Before 7.083°" is indeed 7:41:45 PM (as opposed to 7:41:19 PM which is what the test expects)

So either the expected test results are incorrect, or the calculations are incorrect. Thoughts?

**Comment by Yitzchok** [comment]
I think we need to resync the tests with the java version to make sure they are the same

**Comment by Yitzchok** [comment]
We should really test this against the Java implementation I think I have some code to do it

**Comment by dakom** [comment]
Test results now match java in https://github.com/Yitzchok/Zmanim/pull/12
