### ISSUE TITLE
information on the weekly Torah portion, Rosh Chodesh, 

### ISSUE THREAD

**Issue by avrAhituv** [Yitzchok/Zmanim#13]
Does the project also include information on the weekly Torah portion, Rosh Chodesh, Molad times, etc.?

Thanks for this project!!

avraham.

**Comment by yakatz** [comment]
All should be included.

**Comment by avrAhituv** [comment]
Thanks!
Can you give me an example of how to accept the Torah portion of the week and the times of candle lighting?
I could not find it..

**Comment by Yitzchok** [comment]
You can find it the [JewishCalendar](https://github.com/Yitzchok/JewishCalendar) project but note that it's under GPL

**Comment by avrAhituv** [comment]
תודה רבה!! יישר כח עצום!
