### ISSUE TITLE
Bug in day of year calculation

### ISSUE THREAD

**Issue by BehindTheMath** [Yitzchok/Zmanim#14]
Since this library is a port of [KosherJava](https://github.com/KosherJava/zmanim), I believe that [this bug](https://github.com/KosherJava/zmanim/issues/110) also applies to this library.

I don't know much about C# or .NET, but I believe [these](https://github.com/Yitzchok/Zmanim/blob/f7269ba6e20292c7c6d222474f00ee35c00109f9/src/Zmanim/Calculator/SunTimesCalculator.cs#L185-L196) are the relevant lines.

**Comment by BehindTheMath** [comment]
Turns out I was wrong, at least regarding Java (see [here](https://github.com/KosherJava/zmanim/issues/110#issuecomment-332042090)).

I don't know how arithmetic works in C#, so I believe this should still be looked in to.

**Comment by Yitzchok** [comment]
This seems fine in C# as well
