### ISSUE TITLE
GetDafYomiBavli in jewishCalendar is incorrect

### ISSUE THREAD

**Issue by eladraviv** [Yitzchok/Zmanim#15]
Hi,
When I'm using GetDafYomiBavli() I'm getting the wrong Daf Yomi page number.
For example - GetDafYomiBavli(new DateTime(2017, 10, 15)) returns Sanhedrin page 92, when it shouldv'e been Sanhedrin page 91.

Doing some digging it seems that the page leap is starting at July 1'st, where's:
GetDafYomiBavli(new DateTime(2017, 6, 30)) - returns Bava Basra page 159 (correct)
GetDafYomiBavli(new DateTime(2017, 7, 1)) - returns Bava Basra page 161 (incorrect)

Looking at GetDafYomiBavli method, it seems that the private method GetJulianDay(DateTime date) is incorrect, where's for 30/6/2017 it returns 2457964 and for 1/7/2017 it returns 2457966 (2 days jump).

I'm no expert, but from looking for Julian Day in the internet it seems that even without the misscalculation, GetJulianDay(DateTime date) returns incorrect day number anyways, since the Julian Day for the 30/6/2017 is 2457934/5.

I changed GetJulianDay(DateTime date) and its working fine, and the problem of the wrong Daf Yomi page number is fixed, here is the code i used if it helps:
            int Month = date.Month;
            int Day = date.Day;
            int Year = date.Year;

            if (Month < 3)
            {
                Month = Month + 12;
                Year = Year - 1;
            }
            long JulianDay = Day + (153 * Month - 457) / 5 + 365 * Year + (Year / 4) - (Year / 100) + (Year / 400) + 1721119;

Thanks alot,
Elad.

**Comment by KosherJava** [comment]
@eladraviv I do know that the Java version seems unaffected by this issue. Go to http://www.kosherjava.com/zmanim-project/zmanim-calendar-generator/ and generate a Calendar Type of Full and you will see that the Daf Yomi is correct. Perhaps @Yitzchok has an idea why the .NET port has an issue.

**Comment by eladraviv** [comment]
Hi,
I think this is because Java Calendar.MONTH property is ZERO based, while .NET calendar.Month starts from index 1.
Therefor, the line in the Java project calculating the month in getJulianDay(Calendar calendar) method, did not ported corrctly to .NET, as Java line:
int month = calendar.get(Calendar.MONTH) + 1;
Is not equal to C# .NET line:
int month = calendar.Month + 1;

A simple fix would be just to change the .NET line:
int month = calendar.Month + 1;
to:
int month = calendar.Month;

BTW - my guess is that when it tested it worked fine, because the dafYomiJulianStartDay is also calculated wrong in .NET, same as the given date, and therefor the timespan between those dates dates was correct, and as a result also the Daf yomi (since the only variable matter in the calculation is the days passed between the given date and the dafYomiJulianStartDay).
Untill we got to a differance in the months total days, such as 31 days in July against 30 in June, and the result was 1 day leap.

Thanks,
Elad.

**Comment by Yitzchok** [comment]
This makes sense. Thanks for finding this bug

**Comment by Yitzchok** [comment]
Fixed in commit 2ccb819
