### ISSUE TITLE
Asp.net core mvc example

### ISSUE THREAD

**Issue by greatjack1** [Yitzchok/Zmanim#16]
I saw on your TODO, that you wanted a ASP.NET example, so I built a full web based api using asp.net core mvc and c#. This can be used by any programming language and relies on your zmanim library for the heavy lifting. [A live version to use is available here](https://wyrezmanim.herokuapp.com). Source code is on my github [here](https://github.com/greatjack1/dotnetcoreZmanim)

**Comment by Yitzchok** [comment]
Nice project
