### ISSUE TITLE
Discrepancy between the results retrieved by the Java library and it’s Net Port

### ISSUE THREAD

**Issue by NykUser** [Yitzchok/Zmanim#29]
There is a discrepancy of more then a half a minuet, between the values returned via the Jave API and its Net port.

Jave was tested with [KosherJava Map](https://kosherjava.com/maps/zmanim.html) & [Wyre API](https://wyrezmanim.herokuapp.com/help) Versus [MyZman Program](https://github.com/NykUser/MyZman) that implements the net port

The issue was pointed out on [Mitmachim Forum](https://mitmachim.top/topic/27171/%D7%9C%D7%94%D7%95%D7%A8%D7%93%D7%94-%D7%AA%D7%95%D7%9B%D7%A0%D7%94-%D7%9C%D7%96%D7%9E%D7%A0%D7%99-%D7%94%D7%99%D7%95%D7%9D/48)

**Comment by Yitzchok** [comment]
Can you give an example of the values that has the discrepancies?

- Location 
- Altitude 
- Date
- Calculator used
- Zman returned on KosherJava code vs Zman on the .NET port.

**Comment by NykUser** [comment]
### Sorry for the alarm

After checking some more the results are exactly the same.
The reason for me thinking the is a discrepancy is Wyre's API using the outdated USNO Algorithm and KosherJava Map also defaulting to it.
after compering the USNO vs USNO & NOAA vs NOAA the results are the same by the second.
**Thank You Yitzchok for  your incredible work!**

### Screenshots showing the comparisons:
Compered Jerusalem using [this link to kosherJave map](https://kosherjava.com/maps/zmanim.html?lat=31.78&lng=35.22)
![Jerusalem USNO](https://user-images.githubusercontent.com/83419922/130246581-6255fe88-ca39-48c1-b81e-34ea6b60ee66.jpg)
![Jerusalem NOAA](https://user-images.githubusercontent.com/83419922/130246600-59684f87-f0e6-4b98-bdbb-366baf170c70.jpg)

### More info on USNO vs NOAA from KosherJava
The USNO algorithm was used by many poskim over the years. It does not differentiate between leap and non-leap years. It is now a drop out of date and is not considered as accurate.
Changes to earth’s rotation since the time they were published and other factors contribute to this. Since they do not differentiate between leap and non-leap years, this alone can mean that the data is a day off (something that corrects itself every 4 years).
The USNO website has been down for a while, so I am quoting from memory here, but if I recall correctly it was also designed to be accurate from about the year 1980 to 2050 with lower accuracy at the edges. It was never considered more accurate than one minute.
You can contrast that with the [NOAA algorithm](https://www.esrl.noaa.gov/gmd/grad/solcalc/calcdetails.html) that is based on newer algorithms by Jean Meeus that are considered more accurate.
That said, you will find very small differences between the two. See the old post[ Zmanim Bug Report from the Land of the Midnight Sun](https://kosherjava.com/2008/05/08/zmanim-bug-report-from-the-land-of-the-midnight-sun/) that references the two. You can see the [extract on a study comparing them](https://ui.adsabs.harvard.edu/abs/2018AAS...23115003P/abstract) to have an idea.
That said, none are really accurate due to atmospheric conditions. See The [Novaya Zemlya Effect’s Impact on Zmanim](https://kosherjava.com/2018/08/14/the-novaya-zemlya-effect-impact-on-zmanim/) article that covers this.
