### ISSUE TITLE
Time zone issue with returned DateTimes

### ISSUE THREAD

**Issue by shmulyeng** [Yitzchok/Zmanim#30]
When using the results of the api in an asp.net core application, I noticed the DateTime fields are created with a DateTimeKind.Utc. Since the time is being adjusted to account for the time zone difference, shouldn't it be created as DateTimeKind.Local?

The practical difference to me is how asp.net converts the DateTime to json. The way it's now, a Z is appended to the end of the DateTime string. This causes my javascript (using the moment library) to create a UTC dateTime field. This in turn causes comparisons to be inaccurate.

**Comment by Yitzchok** [comment]
You are right. I think _Kind_ should be set to _Unspecified_.
