### ISSUE TITLE
compatible issues with universal windows project

### ISSUE THREAD

**Issue by hiddai** [Yitzchok/Zmanim#4]
Yitzchok Shalom,

I opened a Universal Windows project in VS Community 2015.
I tried to install Zmanim Nuget package - but it was failed.

![718238](https://cloud.githubusercontent.com/assets/14178415/9736342/421bf4a4-5649-11e5-97fd-36da8132df48.png)

I opened a post about it in Visual Studio Development - a MSDN Forum:
https://social.msdn.microsoft.com/Forums/en-US/070633e2-4d73-4920-b064-fb9d7e88a210/visual-studio-and-java-api?forum=visualstudiogeneral

Please your help solving this problem

thanks

Hiddai

**Comment by Yitzchok** [comment]
We now support .NET Standard 1.3 so it might work for you now.
