### ISSUE TITLE
GPL 

### ISSUE THREAD

**Issue by dsadinoff** [Yitzchok/Zmanim#8]
according to 
https://github.com/Yitzchok/Zmanim/blob/master/src/Zmanim/HebrewCalendar/JewishCalendar.cs

    /// The methods used to obtain the parsha were derived from the source code of <a
    /// href="http://www.sadinoff.com/hebcal/">HebCal</a> by Danny Sadinoff and JCal for the Mac by Frank Yellin. Both based
    /// their code on routines by Nachum Dershowitz and Edward M. Reingold. The class allows setting whether the parsha and
    /// holiday scheme follows the Israel scheme or outside Israel scheme. The default is the outside Israel scheme.

Note that the code due to Dershowitz and Reingold in Emacs are GPL'd and so is hebcal.  I would suggest that you take action to ensure that your'e properly complying with the license of the code you have used.

-Danny

**Comment by dsadinoff** [comment]
NB: https://github.com/KosherJava/zmanim/issues/106/

**Comment by Yitzchok** [comment]
Hi Danny,

Is it only the JewishCalendar class?

As far as I remember all the files in the HebrewCalendar directory isn't included in the project  and if someone want's it they will have to add it and compile it.

I will move it into a separate repository and update the header.

Thanks for bringing it to our attention.

**Comment by Yitzchok** [comment]
Moved it to https://github.com/Yitzchok/JewishCalendar let me know if this works for you.

**Comment by dsadinoff** [comment]
Looks like the license is clear, so I'm fine with it.  Thanks for taking care of this.
